### ISSUE TITLE
Add informative README.

### ISSUE THREAD

**Issue by lidgnulinux** [Astavie/Shatter#1]
Hello, It will be better if there is an informative README file, compilation guide. Also I try to compile it with : 
```
$ zig build -Drelease-safe --prefix ~/.local install
```

I got this : 

```
/home/ahmad/compile/Shatter/build.zig:5:35: error: unable to load '/home/ahmad/compile/Shatter/deps/zig-wayland/build.zig': FileNotFound
const ScanProtocolsStep = @import("deps/zig-wayland/build.zig").ScanProtocolsStep;
```

Do I need to run `git submodule update --init --recursive` ?

Thanks.

**Comment by Astavie** [comment]
Hello! I did not expect someone to find this repo this quickly haha, just started working on this 2 days ago. Right now it doesn't even support any kind of keyboard/mouse input.

To answer your question, `git submodule update --init` is indeed required. The `--recursive` flag should not be needed, however.

**Comment by Astavie** [comment]
The README has been updated!
